# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180601_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauthtoken',
            options={'verbose_name_plural': '用户token表'},
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='app01.Course'),
        ),
    ]
